### PR TITLE
Create sheryel.json

### PR DESCRIPTION
**Pull request by CompactLethargy13**
sheryel is really cool 😃👍

### CODE REVIEW

**Comment by Joabutt** [comment]
Please add more content to your website. We do not tolerate spam websites.

**Comment by CompactLethargy13** [comment]
This website is meaningful and creative, expresses my feelings about "Sheryel", and is very informative to the reader. By looking at the website, they can learn about the word Sheryel and how it looks in different forms, sizes, and colors. I do not understand what you mean, so please accept this pull request. Thank you and have a nice day.

**Comment by Joabutt** [comment]
banned @CompactLethargy13 from this repo.

**Comment by CompactLethargy13** [comment]
bruh

**Pull request merged**
