### PR TITLE
Create vikas.json

### PR DESCRIPTION
**Pull request by zvikasdongre**

### CODE REVIEW

**Comment by Joabutt** [comment]
Nice portfolio!

**Comment by Joabutt** [comment]
After the merge, do remember to add the custom domain vikas.is-really.cool to vercel!

**Comment by zvikasdongre** [comment]
Hello @Joabutt,
First of all Thank you so much for the subdomain. 
and second, I need you to provide me a little help by adding this TXT record as requested by vercel. Let me know once you've added it, I'll verify the sub-domain, and then you can remove the record.

Hope you understand :)

image
 
Type: `TXT`
Name: `_vercel`
Value: `vc-domain-verify=vikas.is-really.cool,d573ce63cade7177558a`

**Comment by Joabutt** [comment]
Got it. I'm now outside, do give me back few hours to resolve it when I'm home. So sorry for the inconvenience.

**Pull request merged**
